# Aggregate Functions in NumPy
# ===============================
### Aggregate functions are used to summarize data.
### They usually take an array as input and return a single value (or summary).
### Examples: sum, mean, max, min, argmin, argmax, etc.

In [9]:
import numpy as np
arr=np.array([
    [2,4,6,8,10],
    [1,3,5,7,9]
])

print("sum of all elements",np.sum(arr))

print("mean(average)",np.mean(arr))

print("maximum value",np.max(arr))

print("minimum value",np.min(arr))

print("index of minimum value",np.argmin(arr))

print("index of maximum value",np.argmax(arr))

#sum across columns (axis=0)
print("column-wise sum",np.sum(arr,axis=0))

#sum across rows (axis=1)
print("row-wise sum",np.sum(arr,axis=1))

# product of all elements
print("product of all elements",np.prod(arr))

# count of array
print(arr.size)

# how many to create  a random array
rand_arr=np.random.randint(1,100,size=39)
print(rand_arr)

sum of all elements 55
mean(average) 5.5
maximum value 10
minimum value 1
index of minimum value 5
index of maximum value 4
column-wise sum [ 3  7 11 15 19]
row-wise sum [30 25]
product of all elements 3628800
10
[12 80 46 63 72 31 36 48 95 66 87 83 66 73 47 63 57 32 32 77 75 28 14 45
 23 75 23  2 28 43 20 98 81 27 46 83 68 14 54]


### reshape

In [12]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
reshaped=arr.reshape(2,3)
reshaped1=arr.reshape(3,2)
print("reshaped():\n",reshaped)
print("reshaped():\n",reshaped1)

reshaped():
 [[1 2 3]
 [4 5 6]]
reshaped():
 [[1 2]
 [3 4]
 [5 6]]


### flatten() -> convert multi dimensional array into 1D
### ravel()


In [14]:
import numpy as np
arr=np.array([
    [2,4,6,8,10],
    [1,3,5,7,9]
])
flat=arr.flatten()
print("flatten():",flat)

# ravel()
flat1=arr.ravel()
print("ravel():",flat1)


flatten(): [ 2  4  6  8 10  1  3  5  7  9]
ravel(): [ 2  4  6  8 10  1  3  5  7  9]


### transpose

In [16]:
import numpy as np
arr=np.array([
    [2,4,6,8,10],
    [1,3,5,7,9]
])
transposed=arr.transpose()
print("transpose():\n",transposed)

transpose():
 [[ 2  1]
 [ 4  3]
 [ 6  5]
 [ 8  7]
 [10  9]]


### vstack and hstack

In [17]:
import numpy as np
A=np.array([[1,2,3]])
B=np.array([[4,5,6]])
vertical=np.vstack((A,B))
horizontal=np.hstack((A,B))

print("verical():\n:",vertical)
print("horizontal():",horizontal)

verical():
: [[1 2 3]
 [4 5 6]]
horizontal(): [[1 2 3 4 5 6]]


### split():- split an array into multiple part

In [20]:
import numpy as np
arr=np.array([10,20,30,40,50,60])
parts=np.split(arr,2)
print("split():\n",parts)

split():
 [array([10, 20, 30]), array([40, 50, 60])]


### unique():-> find unique elements in a array

In [22]:
import numpy as np
a=np.array([1,2,3,4,5,3,4,5])
und=np.unique(a)
print("unique():",und)

unique(): [1 2 3 4 5]
