In [1]:
print("hello world")

hello world


## NUMPY


# numpy multiplication

In [2]:
import numpy as np

lst=[1,2,3,4]

array1=np.array(lst)
result=array1 *2
print(result)

[2 4 6 8]


# numpy division

In [ ]:
import numpy as np

lst=[2,4,6,8]

array=np.array(lst)
result1=array//2
print(result1)


[1 2 3 4]


# numpy addition


In [8]:
lst=[3,6,9,12]
array2=np.array(lst)
result=array + array2
print(result)

[ 5 10 15 20]


# numpy substraction

In [10]:
result=array2 - array
print(result)

[1 2 3 4]


# scalar arithmetic(mathemetical operation on single value)

In [11]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr +1)
print(arr -1)
print(arr *2)
print(arr /4)
print(arr **3)

[2 3 4 5 6]
[0 1 2 3 4]
[ 2  4  6  8 10]
[0.25 0.5  0.75 1.   1.25]
[  1   8  27  64 125]


# vector arithmetic (1D array)

In [13]:
array3=np.array([1,2,3,4,5,6])
array4=np.array([1.0,2.3,5.1,8.6])
print(np.sqrt(array3))
print(np.round(array4))
print(np.floor(array4))
print(np.pi)

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974]
[1. 2. 5. 9.]
[1. 2. 5. 8.]
3.141592653589793


# 2 dimension array(nested array) OR matrix multiplicatio

In [ ]:
import numpy as np

A=np.array([[1,2],
           [3,4]])
B=np.array([[5,6],
           [7,8]])

print(A.shape)#no of rows and columns
print(A*B)

(2, 2)
[[ 5 12]
 [21 32]]


# indexing

In [ ]:
my_list=[[[1,2,3],[4,5,6],[7,8,9]]]
print(my_list)
print(my_list[0][1][1])

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]]]
6


In [ ]:
new_arr =np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(new_arr)
print(new_arr[0][0])
print(new_arr.ndim)# how many dimension
print(new_arr.shape)
print(new_arr[0][0][1]+new_arr[0][1][0])

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]
[1 2 3]
3
(2, 3, 3)
6


# multiple a nested list by 5 using numoy

In [2]:
import numpy as np
nested_list=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
result=np.array(nested_list)
result=result * 5
print(result)

[[ 5 10 15]
 [20 25 30]
 [35 40 45]]


In [6]:
import numpy as np
nested_list=[
    [1,2,3],
    [4,5,6],
    [7,8,9]
]
print(nested_list[0]+nested_list[1])#without using numpy
new_result=np.array(nested_list)
print(new_result[0]+new_result[1])

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [13]:
for i in range(100,0,-2):#descending order in range 
    print(i)

100
98
96
94
92
90
88
86
84
82
80
78
76
74
72
70
68
66
64
62
60
58
56
54
52
50
48
46
44
42
40
38
36
34
32
30
28
26
24
22
20
18
16
14
12
10
8
6
4
2


# slicing

In [ ]:
import numpy as np
lst=[1,2,3,4,5,6,7,8,9]
result=np.array(lst)
print("1.result[1:8]-> element from index 1 to 7 :",result[1:8])
print("2.result[1:]-> element from index 1 to end :",result[1:])
print("3.result[:1]-> element from index 0 :",result[:1])
print("4.result[::-1]-> reverse the lst :",result[::-1])




1.result[1:8]-> element from index 1 to 7 : [2 3 4 5 6 7 8]
2.result[1:]-> element from index 1 to end : [2 3 4 5 6 7 8 9]
3.result[:1]-> element from index 0 : [1]
4.result[::-1]-> reverse the lst : [9 8 7 6 5 4 3 2 1]


#  negative slicing

In [15]:
lst=[1,2,3,4,5,6,7]
arr=np.array(lst)
print("5.arr[-3:-1]-> from 3rd last to 2rd last element:",arr[-3:-1])
print("6.arr[::3]-> every 3rd element :",arr[::3])

5.arr[-3:-1]-> from 3rd last to 2rd last element: [5 6]
6.arr[::3]-> every 3rd element : [1 4 7]


# slicing 2D array

In [19]:
import numpy as np

nested_list1=[
    [1,2,3,5,9,8],
    [4,5,6,7,8,9]

]

new_arr=np.array(nested_list1)
print(new_arr[0, 1:4])
print(new_arr[0:2,1])
print(new_arr[0:2,1:4])

[2 3 5]
[2 5]
[[2 3 5]
 [5 6 7]]
